spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/productdb
    username: productuser
    password: productpass
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
server:
  port: 8080
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
